cora:
  alpha: 0.3
  beta: 0.3
  gamma: 0.3
  attn_dp: 0.6
  feat_dp: 0.7
  backbone: 'gat'
  num_heads: 6
  resi: 1  
  dp_rate: 0.4
  vae_hidden1: 1024
  vae_hidden2: 64
  classifier_dim1: 1024
  classifier_dim2: 512  
  lr: 0.0092
  epochs: 1280
citeseer:
  alpha: 1.0
  beta: 0.7
  gamma: 0.8
  attn_dp: 0.6
  feat_dp: 0
  backbone: 'gcn'
  num_heads: 6
  resi: 1  
  dp_rate: 0.3
  vae_hidden1: 1024
  vae_hidden2: 64
  classifier_dim1: 1024
  classifier_dim2: 1024
  lr: 0.07
  epochs: 370
pubmed:
  alpha: 0.9
  beta: 0
  gamma: 0.3
  attn_dp: 0.8
  feat_dp: 0.5
  backbone: 'gcn'
  num_heads: 8
  resi: 1  
  dp_rate: 0.4
  vae_hidden1: 1024
  vae_hidden2: 64
  classifier_dim1: 1024
  classifier_dim2: 512  
  lr: 0.0175
  epochs: 60
coacs:
  alpha: 0.5
  beta: 0.5
  gamma: 0.4
  attn_dp: 0.6
  feat_dp: 0.6
  backbone: 'gat'
  num_heads: 6
  resi: 1  
  dp_rate: 0.3
  vae_hidden1: 128
  vae_hidden2: 64
  classifier_dim1: 16
  classifier_dim2: 16
  lr: 0.007
  epochs: 960
coaphysics:
  alpha: 0.5
  beta: 0.1
  gamma: 0.1
  attn_dp: 0.6
  feat_dp: 0.6
  backbone: 'gcn'
  num_heads: 6
  resi: 1  
  dp_rate: 0.3
  vae_hidden1: 128
  vae_hidden2: 64
  classifier_dim1: 16
  classifier_dim2: 16
  lr: 0.05
  epochs: 200
coaphoto:
  alpha: 0.2
  beta: 0.2
  gamma: 0.2
  attn_dp: 0.6
  feat_dp: 0.6
  backbone: 'gat'
  num_heads: 6
  resi: 1  
  dp_rate: 0.0
  vae_hidden1: 128
  vae_hidden2: 64
  classifier_dim1: 16
  classifier_dim2: 16
  lr: 0.009
  epochs: 1000
coacomputer:
  alpha: 0.8
  beta: 0.3
  gamma: 0.4
  attn_dp: 0.7
  feat_dp: 0.3
  backbone: 'gcn'
  num_heads: 8
  resi: 0
  dp_rate: 0.1
  vae_hidden1: 256
  vae_hidden2: 512
  classifier_dim1: 1024
  classifier_dim2: 512
  lr: 0.0017
  epochs: 250
